name: Deploy para GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload de arquivos
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # pasta onde estão seus arquivos do site

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
